# Copyright 2026 The Grom Authors
# Distributed under the terms of the BSD license.

cache-format = md5-dict
eapis-banned = 0 1 2 3 4 5 6
masters = portage-stable chromiumos eclass-overlay amd64-generic
profile-formats = portage-2 profile-default-eapi
profile_eapi_when_unspecified = 5-progress
repo-name = grom-amd64
thin-manifests = true
use-manifests = strict
