#!/bin/bash
# Copyright 2026 The Grom Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -euo pipefail

: "${SYSROOT:?SYSROOT must be set by the Portage build environment}"

exec /mnt/host/source/src/platform2/common-mk/platform2_test.py \
	--strategy=sudo \
	--user=root \
	--bind-mount-dev \
	--quiet \
	--sysroot="${SYSROOT}" \
	-- "$@"
